# Generated by Django 3.0.4 on 2020-04-09 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20200409_1430'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='birth',
            field=models.DateField(null=True, verbose_name='Data de nascimento'),
        ),
    ]
