# Generated by Django 3.0.4 on 2020-04-15 00:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_auto_20200414_2146'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Address',
        ),
    ]
