# Generated by Django 3.0.6 on 2020-09-11 00:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_auto_20200423_1157'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cargo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TempoContrato',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TipoContrato',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='confirmacao_agendamentos',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='cpf',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='is_admin',
            field=models.BooleanField(blank=True, default=False, verbose_name='Administrador do sistema'),
        ),
        migrations.AddField(
            model_name='user',
            name='sexo',
            field=models.CharField(blank=True, max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='telefone',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='tipo_endereco',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='tipo_telefone',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.CreateModel(
            name='Funcionario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matricula', models.CharField(max_length=200, null=True)),
                ('data_ini', models.DateField(null=True)),
                ('cargo', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='accounts.Cargo')),
                ('contrato_trabalho', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='accounts.TipoContrato')),
                ('tempo_contrato', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='accounts.TempoContrato')),
                ('usuario', models.OneToOneField(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='usuario', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
