# Generated by Django 3.0.6 on 2020-09-11 01:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_auto_20200910_2145'),
    ]

    operations = [
        migrations.AddField(
            model_name='funcionario',
            name='valor_contrato',
            field=models.DecimalField(decimal_places=2, max_digits=14, null=True),
        ),
    ]
