# Generated by Django 3.0.6 on 2020-09-11 01:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_funcionario_valor_contrato'),
    ]

    operations = [
        migrations.AddField(
            model_name='tempocontrato',
            name='dias',
            field=models.IntegerField(null=True),
        ),
    ]
