# Generated by Django 3.1.1 on 2020-09-22 00:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_remove_user_tipo_endereco'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='fx_salario',
            field=models.CharField(choices=[('Faixa 1', '0-1000'), ('Faixa 2', '1001-3000'), ('Faixa 3', '3001-5000'), ('Faixa 4', '> 5000')], default='Faixa 1', max_length=30, verbose_name='Faixa salario'),
        ),
    ]
