"""
Django settings for salaoecia project.

Generated by 'django-admin startproject' using Django 3.0.4.

For more information on this file, see
https://docs.djangoproject.com/en/3.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.0/ref/settings/
"""

from django.contrib.messages import constants
import os
import django_heroku

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'fpm@_bq!r6zw_%cn^heqch)op!bd^e^iqeme(vyi#s)m0nx=lp'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'salaoecia.salao',
    'salaoecia.core',
    'salaoecia.accounts',

]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
'salaoecia.accounts.middleware.SessionExpiredMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]


ROOT_URLCONF = 'salaoecia.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, "salaoecia/core/Templates"), os.path.join(BASE_DIR, "salaoecia/accounts/Templates")],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'salaoecia.wsgi.application'

# Database
# https://docs.djangoproject.com/en/3.0/ref/settings/#databases

# DATABASES = {
#    'default': {
#        'ENGINE': 'django.db.backends.sqlite3',
#        'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),
#    }
# }

# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.postgresql_psycopg2',
#         'NAME': 'salaoecia',
#         'USER': 'postgres',
#         'PASSWORD': '123456',
#         'HOST': 'localhost',
#         'PORT': '5432',  # 8000 is default
#     }
# }

# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.postgresql_psycopg2',
#         'NAME': 'dcsnb4v8updb5s',
#         'USER': 'uvlwxaiicendtx',
#         'PASSWORD': 'fa2e5e116341eb3dc862f35b3a2def40950d11709deeacdc0993d74ddcfce82b',
#        'HOST': 'ec2-54-159-112-44.compute-1.amazonaws.com',
#         'PORT': '5432',  # 8000 is default
#     }
# }

# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.postgresql_psycopg2',
#         'NAME': 'salaoecia_db',
#         'USER': 'salaoecia_admin@servidor-tcc',
#         'PASSWORD': 'dcsnb4v8updb5s!',
#         'HOST': 'servidor-tcc.postgres.database.azure.com',
#         'PORT': '5432',  # 8000 is default
#     }
# }

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql_psycopg2',
        'NAME': 'postgres',
        'USER': 'salaoecia_admin@salaoecia-tcc',
        'PASSWORD': 'dcsnb4v8updb5s!',
        'HOST': 'salaoecia-tcc.postgres.database.azure.com',
        'PORT': '5432',  # 8000 is default
    }
}

# Honor the 'X-Forwarded-Proto' header for request.is_secure()
SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')

# Password validation
# https://docs.djangoproject.com/en/3.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'salaoecia.accounts.validators.IsActiveValidator',
    },
    {
        'NAME': 'salaoecia.accounts.validators.MinimumLengthValidator',
        'OPTIONS': {
            'max_length': 32,
        }
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
        'OPTIONS': {
            'min_length': 8,
        }
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },

]

AUTHENTICATION_BACKENDS = [
    'salaoecia.accounts.backend.QuantidadeLoginView',
    'django.contrib.auth.backends.AllowAllUsersModelBackend'
]

# Internationalization
# https://docs.djangoproject.com/en/3.0/topics/i18n/

LANGUAGE_CODE = 'pt-br'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.0/howto/static-files/

STATIC_URL = '/static/'

MEDIA_ROOT = os.path.join(BASE_DIR, 'salaoecia', 'media')

MEDIA_URL = '/media/'

MESSAGE_TAGS = {
    constants.DEBUG: 'alert-info',
    constants.ERROR: 'alert-danger',
    constants.INFO: 'alert-info',
    constants.SUCCESS: 'alert-success',
    constants.WARNING: 'alert-warning',
}

# Sessão em dias: 60s * 60m * 24h * 1d
SESSION_COOKIE_AGE = 60 * 60 * 24 * 7

# Salvar a cada requisição
SESSION_SAVE_EVERY_REQUEST = False

# E-mail
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
# EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'
EMAIL_USE_TLS = True
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_HOST_USER = 'willian.will01@gmail.com'
EMAIL_HOST_PASSWORD = 'osubkvoogdktrwxw'
EMAIL_PORT = 587
DEFAULT_FROM_EMAIL = EMAIL_HOST_USER
CONTACT_EMAIL = 'willian.will01@gmail.com'

# Auth
LOGIN_URL = 'login'
LOGIN_REDIRECT_URL = 'salaoecia.salao.urls'
LOGOUT_URL = 'logout'
AUTH_USER_MODEL = 'accounts.User'

ALLOWED_HOSTS = ['*']

# Configure Django App for Heroku.
django_heroku.settings(locals())

# TWILIO SMS
TWILIO_ACCOUNT_SID = os.getenv("AC29e7d49be5aa7fee9f05f836f98b7f55")
TWILIO_AUTH_TOKEN = os.getenv("47c318a0d0d9ae96bd508b5a0cb35edc")
TWILIO_NUMBER = os.getenv("+12083699583")
SMS_BROADCAST_TO_NUMBERS = [
    # "+5541999828545", # Pedro
    "+5541999457987",  # Willian
    "",
]
