# Generated by Django 3.0.6 on 2020-09-03 02:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('salao', '0002_horario_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Agendamento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=14, null=True)),
                ('is_pago', models.BooleanField(default=False, null=True)),
                ('cliente', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
                ('horario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='salao.Horario')),
            ],
        ),
        migrations.AddField(
            model_name='servicos',
            name='valor',
            field=models.DecimalField(decimal_places=2, max_digits=14, null=True),
        ),
        migrations.CreateModel(
            name='AgendamentoServicos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agendamento', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='salao.Agendamento')),
                ('servico', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='salao.Servicos')),
            ],
        ),
    ]
