# Generated by Django 3.0.6 on 2020-09-03 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salao', '0003_auto_20200902_2310'),
    ]

    operations = [
        migrations.AddField(
            model_name='agendamento',
            name='data',
            field=models.DateField(null=True),
        ),
    ]
