# Generated by Django 3.0.6 on 2020-09-03 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salao', '0006_agendamento_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='agendamento',
            name='servicos',
            field=models.ManyToManyField(through='salao.AgendamentoServicos', to='salao.Servicos'),
        ),
    ]
