# Generated by Django 3.0.6 on 2020-09-03 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salao', '0007_agendamento_servicos'),
    ]

    operations = [
        migrations.CreateModel(
            name='MotivosAgendamento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200, null=True)),
                ('status', models.BooleanField(default=True, null=True)),
            ],
        ),
    ]
