# Generated by Django 3.0.6 on 2020-09-10 10:58

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('salao', '0011_produto_produtounidadecomercial'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='dat_insercao',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='produto',
            name='status',
            field=models.BooleanField(default=True, null=True),
        ),
    ]
