# Generated by Django 3.0.6 on 2020-09-10 11:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('salao', '0012_auto_20200910_0758'),
    ]

    operations = [
        migrations.RenameField(
            model_name='produto',
            old_name='estoque_comercial',
            new_name='estoque_minimo',
        ),
        migrations.AddField(
            model_name='produto',
            name='unidade_comercial',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='salao.ProdutoUnidadeComercial'),
        ),
    ]
