# Generated by Django 3.0.6 on 2020-09-10 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salao', '0013_auto_20200910_0802'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='estoque_atual',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='produto',
            name='estoque_atualizado',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='produto',
            name='nome',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
