# Generated by Django 3.0.6 on 2020-09-10 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salao', '0014_auto_20200910_0802'),
    ]

    operations = [
        migrations.AddField(
            model_name='produtounidadecomercial',
            name='status',
            field=models.BooleanField(default=True, null=True),
        ),
    ]
