# Generated by Django 3.1.1 on 2020-09-22 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salao', '0016_auto_20200921_2154'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='tipo',
            field=models.CharField(choices=[('Tintura', 'Tintura'), ('Escova', 'Escova'), ('Lavagem', 'Lavagem'), ('Corte', '> Corte')], default='Tintura', max_length=30, verbose_name='Tipo'),
        ),
    ]
