# Generated by Django 3.0.4 on 2020-11-03 12:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('salao', '0017_auto_20200921_2202'),
    ]

    operations = [
        migrations.CreateModel(
            name='Compra',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pagamento', models.CharField(max_length=200, null=True)),
                ('vlr_total', models.DecimalField(decimal_places=2, max_digits=14, null=True)),
                ('vlr_recebido', models.DecimalField(decimal_places=2, max_digits=14, null=True)),
                ('vlr_troco', models.DecimalField(decimal_places=2, max_digits=14, null=True)),
                ('cpf_na_nota', models.CharField(max_length=200, null=True)),
                ('cliente', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterField(
            model_name='produto',
            name='tipo',
            field=models.CharField(choices=[('Tintura', 'Tintura'), ('Escova', 'Escova'), ('Lavagem', 'Lavagem'), ('Corte', ' Corte')], default='Tintura', max_length=30, verbose_name='Tipo'),
        ),
        migrations.CreateModel(
            name='CompraProduto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('compra', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='salao.Compra')),
                ('produto', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='salao.Produto')),
            ],
        ),
        migrations.CreateModel(
            name='CompraAgendamento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agendamento', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='salao.Agendamento')),
                ('compra', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='salao.Compra')),
            ],
        ),
    ]
