# Generated by Django 3.0.4 on 2020-11-07 03:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('salao', '0018_auto_20201103_0925'),
    ]

    operations = [
        migrations.CreateModel(
            name='Salao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_caixa_aberto', models.BooleanField(default=False, null=True)),
                ('dat_edicao', models.DateTimeField(auto_now=True, null=True)),
                ('usr_edicao', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
