# Generated by Django 3.0.4 on 2020-11-10 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salao', '0021_compra_vlr_parcelado'),
    ]

    operations = [
        migrations.AddField(
            model_name='agendamento',
            name='dat_edicao',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
